//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDB.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class dependencies
    {
        public int dependencyId { get; set; }
        public int dependeeId { get; set; }
        public int dependsOnId { get; set; }
    
        public virtual configurationItem dependee { get; set; }
        public virtual configurationItem dependsOn { get; set; }
    }
}
